### ISSUE TITLE
how to analyzer a web url image?

### ISSUE THREAD

**Issue by zj2050** [vbookshelf/Skin-Lesion-Analyzer#3]
I want to set a  web url image to analyzer ,but is stop at 

	image = $('#selected-image').get(0); //this code can get a image info but next is wrong
	
	// Pre-process the image
	**let tensor = tf.fromPixels(image)
	.resizeNearestNeighbor([224,224])
	.toFloat();**

**Comment by vbookshelf** [comment]
Hi @zj2050 . I have never sent an image to the analyzer using a web url so I can't give you advice on how to do this. The code is designed to accept images that are selected from a computer because tensorflow.js models run locally (on a pc). All I can suggest is that you check that that the image you are passing to tf.fromPixels is of a type that it expects.

**Comment by zj2050** [comment]
@vbookshelf thanks for u, would u provide a frozen's .pb file from model_kaggle files ?
email:  pub123@126.com

thanks

**Comment by vbookshelf** [comment]
You're welcome. I've never used the .pb format before. The trained model is stored in the output of the Kaggle notebook. Please click this link and then click the "Download All" button.
https://www.kaggle.com/vbookshelf/skin-lesion-analyzer-tensorflow-js-web-app/output

**Comment by zj2050** [comment]
> You're welcome. I've never used the .pb format before. The trained model is stored in the output of the Kaggle notebook. Please click this link and then click the "Download All" button.
> https://www.kaggle.com/vbookshelf/skin-lesion-analyzer-tensorflow-js-web-app/output

Thanks a lot!
