### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andreped** [vbookshelf/Skin-Lesion-Analyzer#4]
I cannot see a license for this software. Could you please add a LICENSE.md. As this is an open project where the tool is said to be completely free to use, I guess an MIT license makes the most sense? You could add a license similar to [this repo](https://github.com/andreped/livermask/blob/master/LICENSE.md).

**Comment by vbookshelf** [comment]
Hi @andreped . The code that I've created is completely free to use. However,  the model was trained with data that has a CC BY-NC-SA 4.0 license. This means that the model can't be used for commercial purposes. I considered adding an MIT license to this repo when I first created it. However, I decided not to add it because the MIT license conflicts with the CC BY-NC-SA 4.0 license that covers the training data.

**Comment by andreped** [comment]
OK, but nice to know! I was mostly interested in the source code :] For inspiration when developing my own app(s). Cool project!
